application: pyib
version: 1
runtime: python
api_version: 1

default_expiration: 7d

handlers:
- url: /xn/.*
  script: gae-rest/xn.py
- url: /static/(.*\.(css|js|jpg|png|gif|exe))
  static_files: static/\1
  upload: static/(.*\.(css|js|jpg|png|gif|exe))
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /google9f303401127f9bab.html
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /.*
  script: pyib.py
  
- url: /res/.*
  script: pyib.py